wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.7
    t:
      2:
      - 5
      4: 3.6.7
      5: 0.10.30
      8:
      - 5
